version: '2'
services:
    pentahorest-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/pentahorest/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=pentahorest
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
